name: smartrent_plus
description: "Proyecto SmartRent+ completo"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:        # necesario para localización
    sdk: flutter

  # UI y utilidades
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  provider: ^6.0.5
  intl: ^0.20.2                 # ← actualizado (requerido por flutter_localizations)
  shared_preferences: ^2.5.3

  # Conexión HTTP
  http: ^1.5.0

  # Imágenes / caché
  cached_network_image: ^3.3.1
  image_picker: ^1.2.0

  # Video embebido
  youtube_player_iframe: ^5.1.2
  video_player: ^2.8.6
  chewie: ^1.7.5

  # Mapas y geocodificación
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geocoding: ^2.2.0
  # (Opcional) si usas Google Maps nativo:
  google_maps_flutter: ^2.7.0

  # Importar/Exportar/Compartir
  file_picker: ^8.1.2
  share_plus: ^10.0.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
