name: smartrent_plus
description: "Proyecto SmartRent+ completo y funcional"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"   # rango seguro para Flutter estable

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ðŸ§© UI y utilidades
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  provider: ^6.0.5
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  dio: ^5.4.0
  path_provider: ^2.1.4
  share_plus: ^7.2.2
  file_picker: ^8.1.2
  permission_handler: ^11.3.1   # âœ… requerido para guardar archivos en /Download
  font_awesome_flutter: ^10.7.0 # âœ… Ã­conos de contacto (WhatsApp, correo, etc.)

  # ðŸŒŽ Mapas y geocodificaciÃ³n
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geocoding: ^2.2.0
  google_maps_flutter: ^2.13.1

  # ðŸŽ¥ Video y multimedia
  youtube_player_iframe: ^5.1.2
  video_player: ^2.9.1
  chewie: ^1.7.5
  video_thumbnail: ^0.5.6

  # ðŸŒ HTTP y APIs
  http: ^1.2.2

  # ðŸ“Š EstadÃ­sticas, reportes y visualizaciÃ³n
  lottie: ^3.1.0
  syncfusion_flutter_charts: ^31.2.5
  pdf: ^3.11.0
  printing: ^5.12.0
  open_filex: ^4.7.0

  # ðŸ“± Mejoras adicionales (seguridad y compatibilidad Android/iOS)
  flutter_svg: ^2.0.10+1        # âœ… para iconos vectoriales y grÃ¡ficos SVG modernos

  # ðŸ’³ Pasarela WebPay (Transbank)
  webview_flutter: ^4.4.2       # âœ… Permite abrir la URL de pago dentro de la app
  flutter_inappwebview: ^6.0.0  # âœ… Alternativa avanzada para control total del navegador interno

  app_links: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  # ðŸ–¼ï¸ Archivos de recursos (assets)
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/transbank_logo.png
    - assets/images/facebook_icon.png
    - assets/images/instagram_icon.png
    - assets/images/linkedin_icon.png
    - assets/images/profile_placeholder.png
    - assets/images/web_icon.png
    - assets/images/whatsapp_icon.png
